### PR TITLE
Continuous Delivery for DC/OS with Spinnaker Blog

### PR DESCRIPTION
**Pull request by anelson425**
New blog post

### CODE REVIEW

**Comment by anelson425** [comment]
preview

**Comment by jakekramercerner** [comment]
Could we provide links to
DC/OS
Kubernetes
Spinnaker
the first instance they occur so people can get more information about them if they don't understand what those things are?

**Comment by willgorman** [comment]
Looks like it's missing the link from the Google doc?

**Comment by anelson425** [comment]
I will add those, I didn't even notice them at first. Thanks for seeing that.

**Comment by anelson425** [comment]
Gist with markdown: https://gist.github.com/anelson425/9b9f3919cd4fe2af426752b53c1aceee

Updated Screenshot

**Comment by cchesser** [comment]
👍

**Pull request merged**
