### PR TITLE
Stylize section header, fixed navigation triangle issue and more

### PR DESCRIPTION
**Pull request by sujaysudheenda**
fixed issues:

- Navigation indicator (pixel triangle) disappears when you expand a post #32
- “Recent Posts” and “Github Repos” should be bolded. #33
- Adjust blog post link styling #31
- Green stroke on bottom branded bar should be Cerner green (#7bc143) #34
- Blue stroke above navigation should be Cerner blue (hex #0d94d2) #29

### CODE REVIEW

**Comment by kpshek** [comment]
Thanks @sujaysudheenda!

It looks like that the version of the blog you started editing differed from the version that you submitted this PR against since there are merge conflicts. Can you resolve these merge conflicts and update your branch?

**Comment by sujaysudheenda** [comment]
@kpshek I have updated the branch by merging in latest copy! let me know if this works

**Comment by kpshek** [comment]
Thanks @sujaysudheenda -- sorry I left this PR open for so long!

**Comment by kpshek** [comment]
Deployed in 08eecab

**Pull request merged**
