### PR TITLE
Accessibility and Usability: On the Road to Great UX

### PR DESCRIPTION
**Pull request by jakekramercerner**
Will have to probably modify line endings since I'm on a Windows machine

### CODE REVIEW

**Comment by cchesser** [comment]
I assume we are good if we are good to target a publish date of October 9th? I should be able to get to it then.

**Comment by LvBromberg** [comment]
I am fine with targeting today, Oct 9. I will tweet it this afternoon once published. Thanks all!

**Comment by LvBromberg** [comment]
@jakekramercerner and @cchesser let's make sure the blog language is updated to reflect that this refers to last year's Midwest UX.  Sorry I am just catching this in the google doc.

**Comment by jakekramercerner** [comment]
Good catch - updating now.

**Comment by jakekramercerner** [comment]
@LvBromberg can you review the updates to make sure I got everything?

**Comment by jakekramercerner** [comment]
Fixed!

**Comment by cchesser** [comment]
The only changes I'm having to apply is updating the date to be today and the bullet list (whitespace). Will push / and then publish.

**Comment by cchesser** [comment]
Merged changes: dc97076260cef7b10a39ff3f2570bdb743c73f4b

Pushed the published changes here: 22b8ebe  

Changes haven't reflected in the sight yet. Will post back once they show up.

**Comment by cchesser** [comment]
Published (which had a decent delay): http://engineering.cerner.com/blog/accessibility-and-usability-on-the-road-to-great-ux/

**Pull request closed without merging**
