### PR TITLE
Denisse and Steven recognition blog

### PR DESCRIPTION
**Pull request by jakekramercerner**

### CODE REVIEW

**Comment by cchesser** [comment]
Drat, I just pushed a PR with the changes (#71). Didn't check that you did earlier.

**Comment by jakekramercerner** [comment]
Sorry lol, I know you asked me to review but I figured since you're out of office today I'd take care of it for you

**Comment by cchesser** [comment]
No worries, one thing I noticed when I put mine together was to emphasize some of the english phrases on the Spanish post. Do you want to apply these to yours, or just work off of mine? Also, I resized my image down as the preview looked too large (and just kept one image, which shared the same asset).

**Comment by jakekramercerner** [comment]
I'd say let's just take my PR down and use yours :)

**Pull request closed without merging**
