### PR TITLE
Add blog post for ShipIt XVI

### PR DESCRIPTION
**Pull request by amcginn**
FireShot Capture 006 - ShipIt Day XVI - Engineering Health - localhost

### CODE REVIEW

**Comment by alex-bezek** [comment]
@amcginn I'm new to this project, but random question, do we care about trying to optimize assets? The one gif is almost 12mb. There are online converters, i tried a quick lossy optomizer and dropped every 4th frame since the gif is a bit jumpy anyways and it reduced it to 8mb which is still big but better. Just curiuos what the process is, thanks!

**Comment by anelson425** [comment]
>@amcginn I'm new to this project, but random question, do we care about trying to optimize assets? The one gif is almost 12mb. There are online converters, i tried a quick lossy optomizer and dropped every 4th frame since the gif is a bit jumpy anyways and it reduced it to 8mb which is still big but better. Just curiuos what the process is, thanks!

We haven't had discussions around file sizes in the past but we also haven't had gif's in here in the past. I think it we should reduce the length to show a single motion and keep this smaller. I see this is a demo of the clock, but if you want a bigger demo, lets post it to the Cerner Eng YouTube channel.

**Comment by kpshek** [comment]
I think we should just have a static image rather than the animated gif. The animation doesn't provide a lot of value as-is since it just shows the meter move slightly.

**Comment by amcginn** [comment]
> I think we should just have a static image rather than the animated gif. The animation doesn't provide a lot of value as-is since it just shows the meter move slightly.

I replaced the gif with a static image.

**Pull request merged**
