### PR TITLE
Railsconf 2016 Recop blog post

### PR DESCRIPTION
**Pull request by sambao21**

### CODE REVIEW

**Comment by kpshek** [comment]
@sambao21 - Can you compress/resize these jpgs so we don't have a 20mb blog post 😉 ?

As an aside, you can just create a branch within this repo next time since you're in our organization.

**Comment by sambao21** [comment]
I reduced them to 1024x768. Does that work? I'll know for next time.

**Comment by kpshek** [comment]
Thanks @sambao21, much better. 😄

**Comment by sambao21** [comment]
I've made minor grammatical updates.

**Comment by kpshek** [comment]
Thanks @sambao21!

**Comment by kpshek** [comment]
Deployed in f0893ad

**Pull request merged**
