### PR TITLE
Adding Cerner and iControl blog

### PR DESCRIPTION
**Pull request by anelson425**
cerner and icontrol

### CODE REVIEW

**Comment by JerrodCarpenter** [comment]
Looks good. Thanks for formatting the code sections for me. 👍

**Comment by JerrodCarpenter** [comment]
Wait, will the image render or no?

**Comment by JerrodCarpenter** [comment]
Also, the link looks broken.

**Comment by anelson425** [comment]
>Also, the links looks broken

My bad, I just see the one link to correct right?
 
https://github.com/cerner/cerner.github.io/pull/99/commits/6d11c08755105cdd025f81eec02c89b011c6b496

cerner and icontrol

**Comment by anelson425** [comment]
>Also, the link looks broken.

What image? I didn't see an image in the blog review. I left a comment about that, but didn't get a response and it sounded like you were done reviewing. I can add an image though if needed.

**Comment by JerrodCarpenter** [comment]
> What image? I didn't see an image in the blog review. I left a comment about that, but didn't get a response and it sounded like you were done reviewing. I can add an image though if needed.

I included it on the Jira, but I think I prefer the link to the documentation more. 👍

**Comment by anelson425** [comment]
Ok, as long as you like it, I will leave as is. Sorry, I didn't see that image posted there.

**Pull request merged**
