### PR TITLE
Adding Cerner and the SDLC blog

### PR DESCRIPTION
**Pull request by cchesser**
Adding Cerner and the SDLC blog. Targeting to publish today.

cerner-sdlc

### CODE REVIEW

**Comment by cchesser** [comment]
I'm actually going to update this to not repeat itself on the title (title and the heading at the beginning are repeating themselves).

**Comment by cchesser** [comment]
Applied change to remove the repeated header and regenerated the preview.

**Comment by CernerAgileMatt** [comment]
The Future should be a header and not the last bullet item at the bottom section of the document.

**Comment by cchesser** [comment]
> The Future should be a header and not the last bullet item at the bottom section of the document.

Updated and regenerated the preview.

**Comment by jakekramercerner** [comment]
+1

**Pull request merged**
