### PR TITLE
SREcon18 Recap

### PR DESCRIPTION
**Pull request by jakekramercerner**

### CODE REVIEW

**Comment by anelson425** [comment]
Can you remove the reference to our internal jira queue and add a screenshot please?

**Comment by jakekramercerner** [comment]
My bad, fixed. I'm not able to post screenshots because I've never been able to get Jekyll working on my Windows machine...

**Comment by anelson425** [comment]
srecon18 recap - engineering health

**Comment by anelson425** [comment]
Attached screenshot for @jakekramercerner.

**Comment by jakekramercerner** [comment]
Thanks!

**Pull request merged**
