### PR TITLE
Adding Inspec Delta OSS post

### PR DESCRIPTION
**Pull request by cchesser**
Adding Inspect Delta OSS announcement for publishing on May 11th.

### CODE REVIEW

**Comment by jrperron88** [comment]
Caught a couple issues. Remove "previous stig" in this line
Utilizing inspec_delta, developers will feed the previous STIG, the new STIG, and the profile, into the tool.

Looks like the numbering reverted to 1 instead of 9 on this line.
Once all changes are complete, the feature branch is then compared against the dev branch where code owners and applicable tech experts will then plus +1 the changes.

**Comment by cchesser** [comment]
@rockhold - yeah, that is a byproduct of the Hugo summary capture. I would be fine with removing that heading, since it serves as an intro anyway.

**Comment by cchesser** [comment]
@jrperron88, I applied your feedback in 0f4ef400819761cd8aae4f2c0f5c5bdefe929b3a.

**Comment by cchesser** [comment]
> The opening 'Problem' header renders a bit oddly in the summary of the post. It'll likely come across as a grammar mistake.

@rockhold , removed the Problem header in fd43b0a.

**Review by jrperron88 — APPROVED** [review]

**Comment by rockhold** [comment]
I didn't have a chance to review this internally before it was up for PR, but I'll share some high-level thoughts on the organization of the content, in case you'd like to make any changes before this is published.

At a high level, this is the current flow of the content:
* Touches on security standards, DISA, and STIG
* Mentions Inspec
* Indicates how a STIG is used
* Details the manual process
* Introduces the Delta workflow using inspec_delta
* Concludes by mentioning that inspec_delta has been open-sourced and provides benefits of using it in a summarized fashion

Putting myself in the shoes of someone external to Cerner who knows nothing about this project or the purpose of this blog post, it seems like there would be quite a bit of reading before I get to the part that hooks me - the "what's in it for me" piece. Currently, the announcement that we've open-sourced this project and that it can provide benefits to some specific audience is mostly at the end of the blog post.

Thinking back to some of the other announcements for open-source projects we've done, I really like how this one for Carbon Graphs was organized, as it has a nice opening statement to help people understand what the blog post is about: https://engineering.cerner.com/blog/carbon-graphs-open-source-visualization-api/

I also like how this one on Terra that touches on the audience in the 'Who is Terra UI for?' section: https://engineering.cerner.com/blog/terra-ui/

**Comment by jrperron88** [comment]
Looks wonderful to me!

**Comment by cchesser** [comment]
Sounds good, will go ahead and publish.

**Pull request merged**
