### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by sambao21**
Update the link for the Managing 30000 logging events blog post from "managing-30000-logging-events-per-day-with-splunk" to "Managing-30000-Logging-Events-per-Day-with-Splunk"

### CODE REVIEW

**Comment by kpshek** [comment]
You never change the master branch, only the source branch

**Comment by sambao21** [comment]
The alternative fix is to fix the directory name. I actually think this is a better fix to be consistent with the other posts.

> You never change the master branch, only the source branch

My bad, I'll close and submit another.

**Comment by kpshek** [comment]
Fixed in 94b2168

The issue was that the original post was committed using a case sensitive folder name. I fixed that in a subsequent commit/push (lowercased it) but git didn't push the change to rename the folder that had already been generated during the 'rake delpoy'. My local copy was correct so I didn't see this issue.

So, despite what I said above about never directly committing to the master branch, I had to do just this. :stuck_out_tongue:

```
(master)$ git mv Managing-30000-Logging-Events-per-Day-with-Splunk temp
(master)$ git mv tmp managing-30000-logging-events-per-day-with-splunk
```

**Comment by kpshek** [comment]
Reminder to self - always make sure the file/directory names are lowercased before the initial commit :)

**Pull request closed without merging**
