### PR TITLE
Adding One Cerner Style Icons post

### PR DESCRIPTION
**Pull request by cchesser**
Adding _One Cerner Style Icons_ open-source post, with a target publish date of April 6th.

### CODE REVIEW

**Comment by bradleyofkansas** [comment]
Where is the PR located?

**Comment by anelson425** [comment]
+1

**Comment by cchesser** [comment]
> Where is the PR located?

This is the only pull request which will include this change. We will then generate the site from the markdown.

**Comment by bjankord** [comment]
+1

**Comment by cchesser** [comment]
This has now been published: http://engineering.cerner.com/blog/one-cerner-style-icons/

**Pull request merged**
