### PR TITLE
ISSUE37-Culture Page Fix, formatting, and spelling correction

### PR DESCRIPTION
**Pull request by Kallie-Riff**
[Issue](https://github.com/cerner/cerner.github.io/issues/37) link.
Also did some readability formatting & spelling correction: plethera > plethora

### CODE REVIEW

**Comment by Kallie-Riff** [comment]
New look on smaller screen:
image

**Comment by anelson425** [comment]
+1

**Comment by Kallie-Riff** [comment]
Let's not merge this yet. After looking at it I don't like how close this makes the paragraph sit to the images above. I'm going to make a couple changes to commit.

**Comment by anelson425** [comment]
>Let's not merge this yet. After looking at it I don't like how close this makes the paragraph sit to the images above. I'm going to make a couple changes to commit.

Sounds good, I didn't mind/notice that.

**Comment by Kallie-Riff** [comment]
Ok! It is ready to go now. Took out some unneeded div closing tags and added CSS to keep the paragraphs lined up nicely under the small images.

image

image

**Comment by anelson425** [comment]
The vertical imagery for Share the Love looks like it has more spacing between the image and hte paragraph now than either of the other 2 sections.

**Comment by Kallie-Riff** [comment]
Right, so the code isn't causing this to display off. This is because the images are different sizes. 
Heart: 78px
Chat bubbles: 100px
lightbulb: 110px
I thought about changing the sizes of those images but I wasn't sure if that would be the way to go. Thoughts?

**Comment by anelson425** [comment]
It is probably worth investigating at some point, but we can make that a separate issue as I am not sure where all in the site that these images are used.

**Comment by anelson425** [comment]
+1

**Pull request merged**
